#nome do projeto
spring.application.name=projeto-final-senai-backend/backend

#bd
spring.datasource.url=jdbc:mysql://localhost:3306/paises_db

#credenciais do bd
spring.datasource.username=root
spring.datasource.password=root

#hibernate
spring.jpa.hibernate.ddl-auto=update
